### ISSUE TITLE
玍字

### ISSUE THREAD

**Issue by KIRINPUTRA** [hiankun/poj_ibus_table#1]
使用者報講「玍」字打 bē 出。

**Comment by KIRINPUTRA** [comment]
（不是欠字体。伊有落載花園字体。）

**Comment by hiankun** [comment]
Pháiⁿsè, chitmá chiah khòaⁿ tio̍h... èngkai sī káikoat ah?

**Comment by cyrixhero** [comment]
Tio̍h, íkeng bô būntê
